# Generated by Django 5.2.6 on 2025-12-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_project_last_analyzed_commit_project_repo_structure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='last_analyzed_commit',
        ),
        migrations.RemoveField(
            model_name='project',
            name='repo_structure',
        ),
        migrations.AlterField(
            model_name='project',
            name='github_repo_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ProjectCommit',
        ),
    ]
