# Generated by Django 5.2.6 on 2025-12-05 11:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_project_last_analyzed_commit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='ai_report_feedback',
        ),
        migrations.RemoveField(
            model_name='project',
            name='ai_resume_points',
        ),
        migrations.RemoveField(
            model_name='project',
            name='final_report',
        ),
        migrations.RemoveField(
            model_name='project',
            name='final_report_content',
        ),
        migrations.RemoveField(
            model_name='project',
            name='github_repo_link',
        ),
        migrations.RemoveField(
            model_name='project',
            name='progress_percentage',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='project_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
