# Generated by Django 5.2.5 on 2025-11-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_projectsubmission_ai_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressupdate',
            name='sentiment',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
