# Generated by Django 5.2.5 on 2025-11-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_remove_progressupdate_sentiment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressupdate',
            name='sentiment',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
