# Generated by Django 5.2.5 on 2025-11-18 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_passwordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('image_file', models.ImageField(upload_to='project_artifacts/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('ai_tags', models.JSONField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='authentication.project')),
            ],
        ),
    ]
