# Generated by Django 5.2.5 on 2025-11-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_projectartifact'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ai_report_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
