# Generated by Django 5.2.5 on 2025-11-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ai_resume_points',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
