# Generated by Django 5.2.6 on 2025-11-23 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_remove_progressupdate_ai_code_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressupdate',
            name='code_file',
            field=models.FileField(blank=True, null=True, upload_to='progress_code/'),
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='authentication.project')),
            ],
        ),
        migrations.AddField(
            model_name='progressupdate',
            name='checkpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updates', to='authentication.checkpoint'),
        ),
        migrations.CreateModel(
            name='CodeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('code_content', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('security_score', models.IntegerField(default=0)),
                ('quality_score', models.IntegerField(default=0)),
                ('security_issues', models.TextField(blank=True, null=True)),
                ('optimization_tips', models.TextField(blank=True, null=True)),
                ('ai_feedback', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_reviews', to='authentication.project')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
