# Generated by Django 5.2.6 on 2025-11-24 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0029_progressupdate_code_file_checkpoint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimedAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('assignment_type', models.CharField(choices=[('Code', 'Code'), ('Diagram', 'Diagram'), ('Report', 'Report'), ('Other', 'Other')], default='Other', max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('duration_minutes', models.IntegerField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('assigned_groups', models.ManyToManyField(related_name='assignments', to='authentication.group')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='assignment_submissions/')),
                ('text_content', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ai_verified', models.BooleanField(default=False)),
                ('ai_feedback', models.TextField(blank=True, null=True)),
                ('ai_score', models.IntegerField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='authentication.group')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_assignments', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='authentication.timedassignment')),
            ],
        ),
    ]
