# Generated by Django 5.2.6 on 2025-12-17 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0033_project_ai_report_feedback_project_ai_resume_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_alumni',
        ),
        migrations.RemoveField(
            model_name='project',
            name='relevance_score',
        ),
        migrations.RemoveField(
            model_name='project',
            name='trend_score',
        ),
    ]
