# Generated by Django 5.2.6 on 2025-12-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0034_remove_project_is_alumni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_alumni',
            field=models.BooleanField(default=False),
        ),
    ]
