# Generated by Django 5.2.6 on 2025-12-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0035_project_is_alumni'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='trend_score',
            field=models.FloatField(default=0.0),
        ),
    ]
