# Generated by Django 5.2.6 on 2025-12-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0037_studentactivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsubmission',
            name='logical_fingerprint',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
