# Generated by Django 5.2.6 on 2025-12-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_repo_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
