# Generated by Django 5.2.5 on 2025-11-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_projectsubmission_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsubmission',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
