# Generated by Django 5.2.5 on 2025-11-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_progressupdate_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivaquestion',
            name='audio_tone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
