# Generated by Django 5.2.5 on 2025-11-13 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_vivaquestion_audio_tone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressupdate',
            name='sentiment',
        ),
        migrations.RemoveField(
            model_name='vivaquestion',
            name='audio_tone',
        ),
    ]
