# Generated by Django 5.2.5 on 2025-11-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_progressupdate_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsubmission',
            name='ai_similarity_report',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='ai_suggested_features',
            field=models.TextField(blank=True, null=True),
        ),
    ]
