# Generated by Django 5.2.5 on 2025-11-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_project_ai_report_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='final_report_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
