# Generated by Django 5.2.5 on 2025-11-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_typingstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('GUIDE_GROUP', 'Guide Group'), ('TEAM_GROUP', 'Team Group'), ('DM', 'Direct Message')], default='GUIDE_GROUP', max_length=20),
        ),
    ]
