# Generated by Django 5.2.5 on 2025-11-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_message_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressupdate',
            name='ai_code_review',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progressupdate',
            name='code_file',
            field=models.FileField(blank=True, null=True, upload_to='progress_code/'),
        ),
        migrations.AddField(
            model_name='progressupdate',
            name='completed_tasks',
            field=models.ManyToManyField(blank=True, related_name='completion_updates', to='authentication.task'),
        ),
        migrations.AddField(
            model_name='progressupdate',
            name='design_image',
            field=models.ImageField(blank=True, null=True, upload_to='progress_designs/'),
        ),
    ]
