# Generated by Django 5.2.5 on 2025-11-23 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_progressupdate_ai_code_review_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressupdate',
            name='ai_code_review',
        ),
        migrations.RemoveField(
            model_name='progressupdate',
            name='code_file',
        ),
        migrations.RemoveField(
            model_name='progressupdate',
            name='completed_tasks',
        ),
        migrations.RemoveField(
            model_name='progressupdate',
            name='design_image',
        ),
    ]
