# Generated by Django 5.2.6 on 2025-12-13 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_project_ai_report_feedback_and_more'),
        ('authentication', '0030_timedassignment_assignmentsubmission'),
    ]

    operations = [
    ]
