# Generated by Django 5.2.6 on 2025-12-15 13:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0032_progressupdate_ai_analysis_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ai_report_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='ai_resume_points',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='audit_quality_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='audit_report',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='audit_security_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='final_report',
            field=models.FileField(blank=True, null=True, upload_to='final_reports/'),
        ),
        migrations.AddField(
            model_name='project',
            name='final_report_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='github_repo_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_alumni',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='last_audit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='progress_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='relevance_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Archived', 'Archived')], default='In Progress', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='trend_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='active_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
