# Generated by Django 5.2.6 on 2025-11-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentxp',
            name='avatar_seed',
            field=models.CharField(default='felix', max_length=100),
        ),
        migrations.AddField(
            model_name='studentxp',
            name='avatar_style',
            field=models.CharField(default='avataaars', max_length=50),
        ),
    ]
