# Generated by Django 5.2.6 on 2025-12-01 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('gamification', '0002_studentxp_avatar_seed_studentxp_avatar_style'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VivaScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('feedback', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('examiner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_viva_scores', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viva_scores', to='authentication.project')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viva_scores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
