# Generated by Django 5.2.6 on 2025-12-03 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_vivascore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VivaScore',
        ),
    ]
